## Pytorch

- Tensors ara a specialized data structure that are very similar to arrays and matrices. In pytorch, we use tensors to encode the inputs and outputs of a model, as well as the model's parameters.

- Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. 

- In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data. 

- Tensors are also optimized for automatic differentiation (we’ll see more about that later in the Autograd section). If you’re familiar with ndarrays, you’ll be right at home with the Tensor API.

In [2]:
import torch
import numpy as np

### Initializing a Tensor

- Tensors can be intialized in various ways.

In [3]:
## Directly from data

data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [4]:
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
type(x_data)

torch.Tensor

In [6]:
## From a Numpy array

np_array = np.array(data)
tensor_from_numpy = torch.from_numpy(np_array)

tensor_from_numpy

tensor([[1, 2],
        [3, 4]])

In [7]:
type(tensor_from_numpy)

torch.Tensor

In [8]:
## From another tensor: The new tensor retains the properties(shape, datatype) of the argument tensor, unless explicitly overridden.

x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # overrides the datatype of x_data

print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5359, 0.8317],
        [0.8268, 0.8674]]) 



In [9]:
## With random or constant values: 

## shape is a tuple dimensions. In the function below, it determines the dimensionality of the output tensor.

shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8785, 0.0516, 0.6627],
        [0.3963, 0.6811, 0.2437]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
## Attributes of a Tensor

## Tensor attributes describe their shape, datatype, and the device on which they are stored.

tensor = torch.rand(3,4)

print(f"\n {tensor}\n")

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


 tensor([[0.9765, 0.3475, 0.6092, 0.7743],
        [0.8801, 0.8761, 0.1079, 0.8282],
        [0.5623, 0.0025, 0.5890, 0.7418]])

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations On Tensors

- Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described here.

- Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

- By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [11]:
## We move our tensor to the GPU if available

if torch.cuda.is_available():
  tenor = tensor.to("cuda")

In [12]:
## Standard numpy-like indexing and slicing:

tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

## another method
print(f"Last column: {tensor[:, -1]}")

## assigning 2nd column all values to zero
tensor[:,1] = 0

print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## Joining tensors 

- You can use torch.cat to concatenate a sequence of tensors along a given dimension. Also torch.stack, another tensor joining op that is subtly different from torch.cat.

In [13]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [14]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)    ## by default dim = 0, row wise joining will happen
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [15]:
t2 = torch.cat([tensor, tensor, tensor], dim=1)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [16]:
torch_ones = torch.ones(4,4)
torch_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
torch_zeros = torch.zeros(4,4)
torch_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
torch.cat([torch_ones, torch_zeros])  

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
torch.cat((torch_ones, torch_zeros))  ## both are ok either [] or () when providing tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Arithmetic operations



### Matrix multiplication between two tensors.

In [23]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [21]:
tensor.T  ## transpose of a tensor

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
## Matrix multiplication
y1 = tensor @ tensor.T
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [25]:
## Matrix multiplication
y2 = tensor.matmul(tensor.T)
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [26]:
y3 = torch.rand_like(y1)
y3

tensor([[0.4917, 0.4700, 0.2813, 0.8885],
        [0.4479, 0.7655, 0.2065, 0.6275],
        [0.8797, 0.4310, 0.8548, 0.7509],
        [0.6617, 0.5479, 0.3561, 0.4029]])

In [27]:
## Matrix multiplication
torch.matmul(tensor, tensor.T, out=y3)   ## when we give out=y3 means we want to take shape of y3

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

#### Element-wise product

In [29]:
z1 = tensor * tensor
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [30]:
z2 = tensor.mul(tensor)
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [31]:
z3 = torch.rand_like(tensor)
z3

tensor([[0.8352, 0.8929, 0.5701, 0.2180],
        [0.8442, 0.3897, 0.8291, 0.2098],
        [0.1832, 0.9612, 0.1444, 0.0051],
        [0.9893, 0.6564, 0.8981, 0.8521]])

In [32]:
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

## In-place operations 

- Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

In [33]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge with NumPy

- Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

##### Tensor to NumPy array

In [36]:
t = torch.ones(5)
print(f"t: {t}\n")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])

n: [1. 1. 1. 1. 1.]


In [37]:
## A change in the tensor reflects in the NumPy array.

t.add_(1)
print(f"t: {t}\n")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])

n: [2. 2. 2. 2. 2.]


##### NumPy array to Tensor

In [46]:
n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [47]:
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [48]:
## Changes in the NumPy array reflects in the tensor.

np.add(n, 1, out=n)
print(f"t: {t}\n")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

n: [2. 2. 2. 2. 2.]
