In [1]:
import torch

In [4]:
# Tensors in PyTorch

t1 = torch.tensor(4.)
print(t1)

tensor(4.)


In [5]:
t1.dtype

torch.float32

In [6]:
## Vector

t2 = torch.tensor([1.,2.,4.,6.])

In [7]:
t2

tensor([1., 2., 4., 6.])

In [8]:
t2.dtype

torch.float32

In [10]:
## Matrix

t3 = torch.tensor([
                   [4.,5.,9.],
                   [9.,59.,8.]
])

In [11]:
t3

tensor([[ 4.,  5.,  9.],
        [ 9., 59.,  8.]])

In [12]:
t3.dtype

torch.float32

In [13]:
type(t3)

torch.Tensor

In [14]:
## 3 -dim tensors

t4 = torch.tensor([
                   [[11,23,45],
                    [55,77.,88]],
                   
                   [[111,232.,453],
                    [505,787,868]]
])

In [15]:
t4

tensor([[[ 11.,  23.,  45.],
         [ 55.,  77.,  88.]],

        [[111., 232., 453.],
         [505., 787., 868.]]])

In [17]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [18]:
print(t2)
t2.shape

tensor([1., 2., 4., 6.])


torch.Size([4])

In [19]:
print(t3)
t3.shape

tensor([[ 4.,  5.,  9.],
        [ 9., 59.,  8.]])


torch.Size([2, 3])

In [20]:
print(t4)
t4.shape

tensor([[[ 11.,  23.,  45.],
         [ 55.,  77.,  88.]],

        [[111., 232., 453.],
         [505., 787., 868.]]])


torch.Size([2, 2, 3])

In [21]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [22]:
x_data

tensor([[1, 2],
        [3, 4]])

In [23]:
# tensor operation

x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)  # requires_grad = True means it will calculate gradient automatic for weight
b = torch.tensor(5., requires_grad=True)

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [24]:
## Arithmetic operation

y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [25]:
## to calculate gradient

y.backward()

In [26]:
print('dy/dx: ', x.grad)
print('dy/dw: ', w.grad)
print('dy/db: ', b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


In [27]:
## Tensor Function

t6 = torch.full((3,2), 22)
t6

tensor([[22, 22],
        [22, 22],
        [22, 22]])

In [33]:
## concat

t7 = torch.cat((t6,t6))
t7

tensor([[22, 22],
        [22, 22],
        [22, 22],
        [22, 22],
        [22, 22],
        [22, 22]])

In [35]:
t8 = torch.sin(t7)
t8

tensor([[-0.0089, -0.0089],
        [-0.0089, -0.0089],
        [-0.0089, -0.0089],
        [-0.0089, -0.0089],
        [-0.0089, -0.0089],
        [-0.0089, -0.0089]])